-- 1. Raw Leads Table (Stores granular CRM records + JSONB for infinite scalability)
CREATE TABLE IF NOT EXISTS leads_raw (
    id TEXT PRIMARY KEY,
    full_name TEXT,
    lead_source TEXT,
    lead_status TEXT,
    owner TEXT,
    annual_revenue REAL DEFAULT 0,
    created_time TEXT,
    modified_time TEXT,
    raw_data JSONB -- Stores the entire exact payload returned by Zoho
);

-- Force add JSONB column to existing leads_raw table without data loss
ALTER TABLE leads_raw ADD COLUMN IF NOT EXISTS raw_data JSONB;

-- 2. CRM Deals / Potentials Table
CREATE TABLE IF NOT EXISTS crm_deals (
    id TEXT PRIMARY KEY,
    deal_name TEXT,
    stage TEXT,
    source TEXT,
    owner TEXT,
    amount REAL DEFAULT 0,
    created_time TEXT,
    modified_time TEXT,
    closed_time TEXT,
    raw_data JSONB -- Eliminates data loss for custom attributes
);

-- 3. CRM Contacts Table
CREATE TABLE IF NOT EXISTS crm_contacts (
    id TEXT PRIMARY KEY,
    full_name TEXT,
    email TEXT,
    owner TEXT,
    created_time TEXT,
    modified_time TEXT,
    raw_data JSONB
);

-- 4. CRM Accounts Table
CREATE TABLE IF NOT EXISTS crm_accounts (
    id TEXT PRIMARY KEY,
    account_name TEXT,
    industry TEXT,
    owner TEXT,
    created_time TEXT,
    modified_time TEXT,
    raw_data JSONB
);

-- 5. Sync Logs (Tracks Incremental API Fetches)
CREATE TABLE IF NOT EXISTS sync_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_time TEXT,
    records_fetched INTEGER,
    status TEXT
);

-- 6. AI Briefings Log (Stores historical Markdown AI Reports)
CREATE TABLE IF NOT EXISTS ai_briefings_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_date TEXT UNIQUE,
    markdown_content TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
